root_raw: "dataset/raw"
root: "dataset/processed"
train_dir: "train"
val_dir: "val"
test_dir: "test"
split_ratio: [0.7, 0.15, 0.15]

img_size: 224
batch_size: 64
shuffle_train: true
pin_memory: false
num_workers: 0
persistent_workers: false

train:
  - RandomResizedCrop: {size: 224, scale: [0.8, 1.0]}
  - RandomHorizontalFlip: {p: 0.5}
  - ColorJitter: {brightness: 0.2, contrast: 0.2, saturation: 0.2, hue: 0.02}
  - ToTensor: {}
  # - Normalize: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}

val:
  - Resize: {size: 224}
  - CenterCrop: {size: 224}
  - ToTensor: {}
  # - Normalize: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}

test:
  - Resize: {size: 224}
  - CenterCrop: {size: 224}
  - ToTensor: {}
  # - Normalize: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}